# Generated by Django 3.2.25 on 2024-06-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concatenated_powerpoint', models.BinaryField(blank=True, null=True)),
                ('day_type', models.CharField(choices=[('TH', 'Thursday'), ('SU', 'Sunday'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('SO', 'Soloist'), ('CH', 'Choir')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('original_link', models.URLField(blank=True, null=True)),
                ('original_key', models.CharField(blank=True, max_length=200, null=True)),
                ('verse', models.TextField(blank=True, null=True)),
                ('chords', models.BinaryField(blank=True, null=True)),
                ('powerpoint', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='myapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plan')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='lead_singers',
            field=models.ManyToManyField(blank=True, null=True, related_name='lead_plans', to='myapp.Singer'),
        ),
        migrations.AddField(
            model_name='plan',
            name='musicians',
            field=models.ManyToManyField(blank=True, null=True, related_name='plans', to='myapp.Musician'),
        ),
        migrations.AddField(
            model_name='plan',
            name='singers',
            field=models.ManyToManyField(blank=True, null=True, related_name='plans', to='myapp.Singer'),
        ),
        migrations.AddField(
            model_name='plan',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='plans', through='myapp.PlanSong', to='myapp.Song'),
        ),
        migrations.CreateModel(
            name='MusicianInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_instruments', to='myapp.instrument')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_instruments', to='myapp.musician')),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(related_name='musicians', through='myapp.MusicianInstrument', to='myapp.Instrument'),
        ),
    ]
