version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3002:3002"
    command: >
      sh -c "npm install &&
             npm run build &&
             npm start"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - frontend-build:/app/frontend/build  # Mount the frontend build directory
    depends_on:
      - db
      - frontend
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/myproject
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8002"

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTHTOKEN=your_ngrok_auth_token  # Replace with your ngrok auth token
      - NGROK_PORT=backend:8002  # This points ngrok to your Django backend


volumes:
  postgres_data:
  frontend-build: